name: Datadog Software Composition Analysis

on:
  workflow_dispatch:
    inputs:
      dd_api_key:
        description: 'Target org API key'
        required: true
      dd_app_key:
        description: 'Target org App key'
        required: true
      dd_site:
        description: 'Datadog site'
        required: false
        default: 'datadoghq.com'

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Mask keys
        run: |
          echo "::add-mask::${{ inputs.dd_api_key }}"
          echo "::add-mask::${{ inputs.dd_app_key }}"

      - name: Check imported libraries are secure and compliant
        uses: DataDog/datadog-sca-github-action@a913b0089df4f91a6fc2ebd50e93efe97a2980b2
        with:
          dd_api_key: ${{ inputs.dd_api_key }}
          dd_app_key: ${{ inputs.dd_app_key }}
          dd_site: ${{ inputs.dd_site }}
